services:
  svelte-alertmanager-dashboard:
    build: .
    env_file:
      - path: ./.env.example
      - path: ./.env
        required: false
    ports:
      - ${DOCKER_HTTP_PORT}:3000
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./src